# Generated by Django 3.1.1 on 2020-11-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0032_auto_20201113_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('L', 'Leve'), ('G', 'Grave'), ('M', 'Muy Grave')], default='L', max_length=1, verbose_name='categoría')),
                ('descripcion', models.TextField(verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaDisciplinariaEstudiantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se cometió la falta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('falta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.falta')),
            ],
        ),
    ]
