# Generated by Django 3.1.1 on 2020-11-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_auto_20201113_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='codigo',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='código'),
            preserve_default=False,
        ),
    ]
