# Generated by Django 3.2.10 on 2025-01-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_faltadisciplinariaestudiantil_periodo_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='faltadisciplinariaestudiantil',
            name='docente_que_reporta',
            field=models.CharField(default='--', max_length=10, verbose_name='Docente que reporta'),
        ),
    ]
