# Generated by Django 5.2.3 on 2025-09-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplina", "0004_faltadisciplinariaestudiantil_docente_que_reporta"),
        ("escuela", "0006_alter_seccion_seccion"),
        ("personas", "0014_alter_estudiante_estudiantes_en_la_misma_casa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demerito",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=3, verbose_name="código")),
                (
                    "descripcion",
                    models.CharField(max_length=100, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "demérito",
                "verbose_name_plural": "deméritos",
            },
        ),
        migrations.AlterField(
            model_name="faltadisciplinariaestudiantil",
            name="docente_que_reporta",
            field=models.CharField(
                default="", max_length=50, verbose_name="Docente que reporta"
            ),
        ),
        migrations.CreateModel(
            name="DemeritoDeEstudiante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(help_text="Fecha en que se cometió el demérito"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=150, verbose_name="Descripción"),
                ),
                (
                    "docente_que_reporta",
                    models.CharField(
                        default="", max_length=50, verbose_name="Docente que reporta"
                    ),
                ),
                (
                    "demerito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="disciplina.demerito",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.estudiante",
                    ),
                ),
                (
                    "periodo_escolar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="escuela.periodoescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "demérito de estudiante",
                "verbose_name_plural": "deméritos de estudiantes",
            },
        ),
    ]
