# Generated by Django 5.2.3 on 2025-09-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplina", "0005_demerito_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demerito",
            name="codigo",
            field=models.CharField(max_length=3, unique=True, verbose_name="código"),
        ),
    ]
