# Generated by Django 5.2.3 on 2025-09-01 02:27

from django.db import migrations


def poblar_datos_demeritos(apps, schema_editor):
    # Obtenemos el modelo histórico
    demeritos = apps.get_model("disciplina", "Demerito")

    # Creamos las instancias
    demeritos.objects.bulk_create(
        [
            demeritos(
                codigo="01", descripcion="No saludar al entrar o al salir del aula"
            ),
            demeritos(
                codigo="02", descripcion='Omitir "Por Favor" al hacer una petición.'
            ),
            demeritos(
                codigo="03",
                descripcion='Omitir "Gracias" al recibir un favor, material o atención.',
            ),
            demeritos(
                codigo="04",
                descripcion="Usar un tono grosesero o irrespetuoso hacia compañeros, docente o personal.",
            ),
        ]
    )


def limpiar_datos_demeritos(apps, schema_editor):
    # En la operación inversa
    demeritos = apps.get_model("disciplina", "Demerito")
    codigos_a_borrar = ["01", "02", "03", "04"]
    demeritos.objects.filter(nombre__in=codigos_a_borrar).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("disciplina", "0006_alter_demerito_codigo"),
    ]

    operations = [
        migrations.RunPython(
            poblar_datos_demeritos, reverse_code=limpiar_datos_demeritos
        ),
    ]
