# Generated by Django 5.2.3 on 2025-09-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disciplina", "0007_poblar_demeritos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demerito",
            options={
                "ordering": ["codigo"],
                "verbose_name": "demérito",
                "verbose_name_plural": "deméritos",
            },
        ),
    ]
