# Generated by Django 5.2.5 on 2026-02-18 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplina", "0008_alter_demerito_options"),
        ("escuela", "0006_alter_seccion_seccion"),
        ("personas", "0014_alter_estudiante_estudiantes_en_la_misma_casa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redencion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=3, unique=True, verbose_name="código"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=100, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "redención",
                "verbose_name_plural": "redenciones",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="RedencionDeEstudiante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(help_text="Fecha en que se cometió la redención"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=150, verbose_name="Descripción"),
                ),
                (
                    "docente_que_reporta",
                    models.CharField(
                        default="", max_length=50, verbose_name="Docente que reporta"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.estudiante",
                    ),
                ),
                (
                    "periodo_escolar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="escuela.periodoescolar",
                    ),
                ),
                (
                    "redencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="disciplina.redencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "redención de estudiante",
                "verbose_name_plural": "redenciones de estudiantes",
            },
        ),
    ]
