# Generated by Django 3.2.10 on 2022-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_de_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Digitador')], default=3),
        ),
    ]
