# Generated by Django 3.2.3 on 2021-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_de_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Digitador')], default=1),
        ),
    ]
