# Generated by Django 5.2.3 on 2025-08-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tipo_de_usuario",
        ),
    ]
