# Generated by Django 5.2.3 on 2025-08-31 17:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_remove_user_tipo_de_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[],
            options={
                "verbose_name": "grupo de usuarios",
                "verbose_name_plural": "grupos de usuarios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
