# Generated by Django 3.1.1 on 2020-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_auto_20200929_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del período escolar, por ejemplo: "Año escolar 2020', max_length=50)),
                ('fecha_de_inicion', models.DateField(help_text='Ingrese la fecha de inicio del período escolar')),
                ('fecha_de_cierre', models.DateField(help_text='Ingrese la fecha de cierre del período escolar')),
            ],
        ),
        migrations.AlterField(
            model_name='seccion',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='sección'),
        ),
    ]
