# Generated by Django 3.1.1 on 2020-09-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20200929_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='periodo_escolar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.periodoescolar'),
            preserve_default=False,
        ),
    ]
