# Generated by Django 3.1.1 on 2020-09-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_seccion_periodo_escolar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveleducativo',
            options={'verbose_name_plural': 'Niveles educativos.'},
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'verbose_name_plural': 'Períodos Escolares'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
