# Generated by Django 3.1.1 on 2020-11-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_auto_20200929_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodoescolar',
            old_name='fecha_de_inicion',
            new_name='fecha_de_inicio',
        ),
    ]
