# Generated by Django 5.1.4 on 2025-01-17 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escuela", "0006_alter_seccion_seccion"),
        ("personas", "0012_alter_estudiante_estudiantes_en_la_misma_casa"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaSeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "seccion",
                    models.ForeignKey(
                        limit_choices_to={"periodo_escolar__periodo_activo": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escuela.seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia de sección",
                "verbose_name_plural": "Asistencias de secciones",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("asistio", models.BooleanField()),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"activo": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.estudiante",
                    ),
                ),
                (
                    "asistencia_de_seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asistencia.asistenciaseccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia de estudiante",
                "verbose_name_plural": "Asistencias de estudiantes",
            },
        ),
    ]
