# Generated by Django 3.1.1 on 2020-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20200929_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='posee_partida',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seccion_previa',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
    ]
