# Generated by Django 3.1.1 on 2020-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20200930_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nie',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
