# Generated by Django 3.1.1 on 2020-09-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20200930_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='posee_tables',
            new_name='posee_tablet',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dependencia_economica',
            field=models.CharField(choices=[('M', 'Madre'), ('D', 'Padre'), ('P', 'Padre y madre'), ('F', 'Otro familiar'), ('S', 'Solo'), ('O', 'Otros')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='etnia',
            field=models.CharField(choices=[('N', 'Ninguna'), ('K', 'Kakawira'), ('L', 'Lenca'), ('N', 'Nahuat - Pipil')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='municipio',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.municipio', verbose_name='Municipio de nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(choices=[('S', 'Salvadoreña'), ('H', 'Hondureña'), ('G', 'Guatemalteca'), ('N', 'Nicaragüense'), ('C', 'Costaricence'), ('P', 'Panameña'), ('E', 'Estadounidense'), ('O', 'Otros')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_celular_con_acceso_a_internet',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_energia',
            field=models.BooleanField(default=True, verbose_name='Posee energía eléctrica'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_radio',
            field=models.BooleanField(default=True, verbose_name='Posee radio o equipo de sonido'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_refrigerador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='posee_televisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='roommate',
            field=models.CharField(choices=[('M', 'Madre'), ('D', 'Padre'), ('P', 'Padre y madre'), ('F', 'Otro familiar'), ('S', 'Solo'), ('O', 'Otros')], default='P', max_length=1, verbose_name='Personas con que vive el estudiante'),
        ),
    ]
