# Generated by Django 3.1.1 on 2020-09-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20200930_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
