# Generated by Django 3.1.1 on 2020-09-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_delete_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo_electronico',
            field=models.EmailField(default='user@mail.com', max_length=254, verbose_name='Correo electrónico personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto 1'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto 2'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='correo_electronico',
            field=models.EmailField(default='user@mail.com', max_length=254, verbose_name='Correo electrónico personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto 1'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto 2'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='compania_internet',
            field=models.CharField(blank=True, choices=[('T', 'Tigo'), ('C', 'Claro'), ('J', 'Japi'), ('O', 'Otro')], help_text='Si posee internet residencial indique la compañia.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='distancia',
            field=models.PositiveSmallIntegerField(help_text='Ingrese la distancia en KM de la vivienda del estudiante al centro educativo.', verbose_name='Distancia de vivienda'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, help_text='Ingrese a menores de edad que vivien con el estudiante y que son estudiantes de la institución educativa', related_name='_estudiante_hermanos_+', to='personas.Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nie',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='NIE'),
        ),
    ]
