# Generated by Django 3.1.1 on 2020-09-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_auto_20200929_2311'),
        ('personas', '0007_auto_20200930_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenorDeEdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.DateField()),
                ('estudia', models.BooleanField(verbose_name='¿El menor estudia?')),
                ('medio_de_transporte', models.CharField(blank=True, choices=[('B', 'Bicicleta'), ('V', 'Vehiculo'), ('P', 'Transpote Público'), ('E', 'Transporte Escolar'), ('M', 'Motocicleta'), ('C', 'Camina'), ('O', 'Otro')], help_text='Medio de transporte principal del menor', max_length=1, null=True)),
                ('institucion_educativa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela', verbose_name='Institución Educativa del menor')),
            ],
        ),
    ]
