# Generated by Django 3.1.1 on 2020-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_menordeedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='menores_cohabitantes',
            field=models.ManyToManyField(help_text='Menores de edad que viven junto al estudiante y que no son estudiantes de la institución.', to='personas.MenorDeEdad'),
        ),
    ]
