# Generated by Django 3.1.1 on 2020-09-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_estudiante_menores_cohabitantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='menores_cohabitantes',
        ),
    ]
