# Generated by Django 3.1.1 on 2020-09-30 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_remove_estudiante_menores_cohabitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='hermanos',
            field=models.ManyToManyField(blank=True, help_text='Ingrese a menores de edad que vivien con el estudiante yque son estudiantes de la institución educativa', related_name='_estudiante_hermanos_+', to='personas.Estudiante'),
        ),
        migrations.CreateModel(
            name='EstudiantesMenores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('menor_de_edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.menordeedad')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='menores_cohabitantes',
            field=models.ManyToManyField(help_text='Ingrese a menores de edad que vivien con el estudiante y que no son estudiantes de la institución educativa', through='personas.EstudiantesMenores', to='personas.MenorDeEdad'),
        ),
    ]
