# Generated by Django 5.1.4 on 2025-01-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0011_alter_estudiante_seccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="estudiantes_en_la_misma_casa",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ingrese estudiantes que viven en la misma casa.",
                to="personas.estudiante",
            ),
        ),
    ]
