# Generated by Django 3.1.1 on 2020-10-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_auto_20200930_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstudiantesMenores',
            new_name='EstudiantesYMenores',
        ),
        migrations.AlterModelOptions(
            name='estudiantesymenores',
            options={'verbose_name': 'Estudiantes y Menores en la misma casa', 'verbose_name_plural': 'Estudiantes y Menores en la misma casa'},
        ),
    ]
