# Generated by Django 3.1.1 on 2020-10-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_auto_20200930_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menordeedad',
            options={'verbose_name_plural': 'Menores de edad'},
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nivel_a_matricular',
            new_name='grado_matriculado',
        ),
    ]
