# Generated by Django 3.2.10 on 2025-01-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_alter_estudiante_estudiantes_en_la_misma_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estudiantes_en_la_misma_casa',
            field=models.ManyToManyField(blank=True, help_text='Ingrese estudiantes que viven en la misma casa.', related_name='_personas_estudiante_estudiantes_en_la_misma_casa_+', to='personas.Estudiante'),
        ),
    ]
