# Generated by Django 5.2.3 on 2025-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0013_alter_estudiante_estudiantes_en_la_misma_casa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="estudiantes_en_la_misma_casa",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ingrese estudiantes que viven en la misma casa.",
                to="personas.estudiante",
            ),
        ),
    ]
