# Generated by Django 3.1.1 on 2020-10-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20200930_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='autorizado_a_tramites',
            field=models.BooleanField(default=False, verbose_name='Está autorizado a realizar trámites'),
            preserve_default=False,
        ),
    ]
