# Generated by Django 3.1.1 on 2020-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_auto_20201001_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='hermanos',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estudiantes_en_la_misma_casa',
            field=models.ManyToManyField(blank=True, help_text='Ingrese a menores de edad que vivien con el estudiante y que son estudiantes de la institución educativa', related_name='_estudiante_estudiantes_en_la_misma_casa_+', to='personas.Estudiante'),
        ),
    ]
