# Generated by Django 3.1.1 on 2020-10-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_auto_20200929_2311'),
        ('personas', '0018_auto_20201001_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='posee_partida',
            field=models.BooleanField(default=True, help_text='Si el estudiante no posee partida de nacimiento se debe demostrar un trámite áctivo para obtenerla.', verbose_name='Posee partida de nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='distancia',
            field=models.PositiveSmallIntegerField(help_text='Ingrese la distancia en KM de la vivienda del estudiante al centro educativo.', verbose_name='Distancia de vivienda al centro escolar'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado_matriculado',
            field=models.ForeignKey(help_text='Nivel educativo en que el estudiante queda matriculado', on_delete=django.db.models.deletion.CASCADE, to='escuela.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='roommate',
            field=models.CharField(choices=[('M', 'Madre'), ('D', 'Padre'), ('P', 'Padre y madre'), ('F', 'Otro familiar'), ('S', 'Solo'), ('O', 'Otros')], default='P', max_length=1, verbose_name='Personas con quienes vive el estudiante'),
        ),
    ]
