# Generated by Django 3.1.1 on 2020-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0021_estudiante_municipio_de_residencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='discpacidad_motora',
            new_name='discapacidad_motora',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='otro',
            field=models.CharField(default=False, help_text='Describa cualquier condición adicional de salud.', max_length=100),
            preserve_default=False,
        ),
    ]
