# Generated by Django 3.1.1 on 2020-10-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0022_auto_20201001_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='otro',
            field=models.CharField(blank=True, help_text='Describa cualquier condición adicional de salud.', max_length=100, null=True),
        ),
    ]
