# Generated by Django 3.1.1 on 2020-10-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0023_auto_20201001_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantesymenores',
            options={'verbose_name': 'Menores que habitan en la misma casa con el estudiante', 'verbose_name_plural': 'Menores que habitan en la misma casa con el estudiante'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'verbose_name': 'Familiar', 'verbose_name_plural': 'Familiares'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_de', to='personas.responsable'),
        ),
    ]
