# Generated by Django 3.1.1 on 2020-10-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0024_auto_20201001_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion_de_residencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de residencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Persona autorizada a hacer trámites del estudiantes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_de', to='personas.responsable'),
        ),
    ]
