# Generated by Django 3.1.1 on 2020-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0025_auto_20201001_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='down',
            field=models.BooleanField(default=False, verbose_name='Síndrome down'),
        ),
    ]
