# Generated by Django 3.1.1 on 2020-11-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0029_auto_20201107_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='menores_cohabitantes',
            field=models.ManyToManyField(help_text='Ingrese a menores de edad que viven con el estudiante y que no son estudiantes de la institución educativa', through='personas.EstudiantesYMenores', to='personas.MenorDeEdad'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='familiar',
            field=models.ForeignKey(help_text='Seleccione un familiar para el estudiante', on_delete=django.db.models.deletion.CASCADE, to='personas.responsable'),
        ),
    ]
