# Generated by Django 3.1.1 on 2020-11-13 15:29

from django.db import migrations, models
import personas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0031_estudiante_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(validators=[personas.validators.validate_date_is_past]),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='fecha_de_nacimiento',
            field=models.DateField(validators=[personas.validators.validate_date_is_past]),
        ),
    ]
