# Generated by Django 3.1.1 on 2020-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0032_auto_20201113_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion_previa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('N', 'Nuevo ingreso')], help_text='Solo si estudió en esta institución(CEDHRA) el año escolar anterior', max_length=1),
        ),
    ]
