# Generated by Django 3.1.1 on 2020-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0033_auto_20201114_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion_previa',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('N', 'Nuevo ingreso')], help_text='Si el estudiante proviene de otra institución o no estudió el año escolar anterior seleccione nuevo ingreso.', max_length=1),
        ),
    ]
