# Generated by Django 3.1.1 on 2020-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0034_auto_20201114_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Ingrese información adicional relevante, como uso de otros documentos que no son DUI o alguna particularidad', null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='dui',
            field=models.CharField(max_length=25, unique=True, verbose_name='DUI'),
        ),
    ]
