# Generated by Django 3.1.3 on 2021-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0036_auto_20201123_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='relacion_de_responsable',
            field=models.CharField(choices=[('P', 'Padre'), ('M', 'Madre'), ('T', 'Tío/Tía'), ('A', 'Abuelo/Abuela'), ('H', 'Hermano/Hermana'), ('O', 'Otros')], default='M', max_length=1, verbose_name='Relación familiar de responsable con estudiante.'),
        ),
    ]
