# Generated by Django 3.1.3 on 2021-01-17 04:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_auto_20201107_1408'),
        ('personas', '0037_estudiante_relacion_de_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='grado_matriculado', chained_model_field='nivel', default=24, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='escuela.seccion', verbose_name='Sección'),
            preserve_default=False,
        ),
    ]
