# Generated by Django 3.1.3 on 2021-01-20 02:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_auto_20201107_1408'),
        ('personas', '0038_auto_20210116_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='grado_matriculado', chained_model_field='nivel_educativo', on_delete=django.db.models.deletion.CASCADE, to='escuela.seccion', verbose_name='Sección'),
        ),
    ]
