# Generated by Django 3.1.5 on 2021-02-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0039_auto_20210119_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='responsable',
            field=models.ForeignKey(help_text='Persona autorizada a hacer trámites del estudiantes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsable_de', to='personas.responsable'),
        ),
    ]
