# Generated by Django 3.1.5 on 2021-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0040_auto_20210202_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_de_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='motivo_de_retiro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='retirado',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante se retira de la institución'),
        ),
    ]
