# Generated by Django 3.2.9 on 2021-11-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0043_alter_estudiante_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='seccion_previa',
        ),
    ]
