# Generated by Django 3.2.9 on 2021-11-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_auto_20210523_2211'),
        ('personas', '0044_remove_estudiante_seccion_previa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='seccion2022',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seccion_2022', to='escuela.seccion', verbose_name='Sección 2022'),
        ),
    ]
