# Generated by Django 3.2.9 on 2021-11-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_auto_20210523_2211'),
        ('personas', '0045_estudiante_seccion2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado_matriculado',
            field=models.ForeignKey(help_text='Nivel educativo en que el estudiante queda matriculado', null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.niveleducativo'),
        ),
    ]
