# Generated by Django 3.2.9 on 2021-11-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_auto_20210523_2211'),
        ('personas', '0046_alter_estudiante_grado_matriculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion2022',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seccion_2022', to='escuela.seccion', verbose_name='Sección 2022'),
        ),
    ]
